### ISSUE TITLE
hasslife在app中无法找到

### ISSUE THREAD

**Issue by ricky6liu** [Blear/HassLife#1]
hasslife在app中无法在天猫精灵app上找到入口添加绑定 app版本6.4.2

**Comment by ricky6liu** [comment]
> hasslife在app中无法在天猫精灵app上找到入口添加绑定

**Comment by Blear** [comment]
什么型号的音箱，是不是第三方的内置猫精服务的

**Comment by Blear** [comment]
https://market.m.taobao.com/app/forest/assets/download.html?redirectUrl=assistant://skill_detail?skillId=71788&share_target=copy_text
如果是官方的猫精型号，试试这个链接

**Comment by Rich-xuguo** [comment]
手机天猫精灵app里，找不到hasslife技能
