### ISSUE TITLE
HomeAssistant地址如使用ipv6地址就无法保存

### ISSUE THREAD

**Issue by 453974158** [Blear/HassLife#16]
在HomeAssistant基础配置中，如果使用ipv6地址则提示“HomeAssistent地址不正确(需要http://开头)!”，导致无法保存。

**Comment by Blear** [comment]
建议选择插件通信控制，安装hasslife插件打开穿透模式，url里面可以随意填写个地址 比如http://192.168.1.1:8123或https://www.baidu.com
