### ISSUE TITLE
长期令牌信息

### ISSUE THREAD

**Issue by biyung168** [Blear/HassLife#4]

**Comment by Blear** [comment]
麻烦问题描述清楚些哈

**Comment by biyung168** [comment]
長期令牌信息是如何設置？

Blear ***@***.***>於 2022年10月13日 週四，12:34寫道：

**Comment by Blear** [comment]
长期令牌进入home assistant在左边侧边栏点击头像滚动到最底部【长期访问令牌】处创建。
令牌请完整复制。

**Comment by Blear** [comment]
建议同时安装插件，插件用来上报设备的开关状态。如果安装了插件，可以在hasslife网站信息设置页面打开穿透功能。无需配置令牌信息 即可控制。
