### ISSUE TITLE
自动通知无法关闭

### ISSUE THREAD

**Issue by flyibeat** [Blear/HassLife#6]
启动ha后，自动通知内容无法设置为不提醒

**Comment by Blear** [comment]
UI界面没有提供通知设置功能，你可以手动修改插件目录的__init__.py文件，找到83行位置，删除以下内容，重启ha即可屏蔽通知
`    if not cfg.get("disablenotify", False):
        hass.components.persistent_notification.async_create(
            "Welcome to hasslife!", "hasslife Infomation", "hasslife_notify")`
