### ISSUE TITLE
不能添加设备

### ISSUE THREAD

**Issue by JQLove2023** [Blear/HassLife#7]
![image](https://github.com/Blear/HassLife/assets/146057668/77ac4eaa-ac08-4c9a-83ff-2e3e5c86e1c6)
请问hasslife平台还在运作吗？谢谢您

**Comment by Blear** [comment]
[你好，正常运作，图中的情况是因为你的公网地址无法访问，如果安装了插件，请在](https://hass.blear.cn/information.php) 页面打开【内网穿透功能】

**Comment by JQLove2023** [comment]
<img width="875" alt="image" src="https://github.com/Blear/HassLife/assets/146057668/1333e931-4d43-44c9-9d0a-a88339a7fcb1">
<img width="941" alt="image" src="https://github.com/Blear/HassLife/assets/146057668/40cb8efd-a5de-42a2-8560-e880c07ee686">
还是不行，能帮帮忙吗？谢谢您

**Comment by Blear** [comment]
重启homeassistant试过吗？

**Comment by JQLove2023** [comment]
试过了

**Comment by JQLove2023** [comment]
还是不可以。请问有解决方案吗？ 谢谢您

**Comment by Blear** [comment]
辛苦加我下qq 我帮你看下

**Comment by Blear** [comment]
723712241

**Comment by JQLove2023** [comment]
谢谢您:)

**Comment by JQLove2023** [comment]
加了。谢谢您
